# Generated by Django 5.0.4 on 2024-06-12 14:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Employee_ID', models.CharField(help_text='Enter a 9-digit employee ID.', max_length=9, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='ID must be exactly 9 digits.', regex='^\\d{9}$')])),
                ('First_Name', models.CharField(default='', max_length=10)),
                ('Last_Name', models.CharField(default='', max_length=10)),
                ('Birthday', models.DateField()),
                ('Email', models.EmailField(max_length=254, verbose_name='')),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be between 9 and 15 digits.', regex='^\\d{9,15}$')])),
                ('Join_Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('online_order', 'Online Order'), ('desk_order', 'Desk Order')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Orders_From_Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True, verbose_name='Order Date')),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view_orders', 'View Orders'), ('edit_orders', 'Edit Orders'), ('view_stock', 'View Stock'), ('edit_stock', 'Edit Stock'), ('view_supplier_orders', 'View Orders from Suppliers'), ('edit_supplier_orders', 'Edit Orders from Suppliers'), ('view_schedule', 'View Scheduling'), ('edit_schedule', 'Edit Scheduling'), ('view_reports', 'View Reports'), ('edit_reports', 'Edit Reports'), ('view_control', 'View Control'), ('edit_control', 'Edit Control')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=50)),
                ('Price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Raw_Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material_Name', models.CharField(max_length=50, verbose_name='Material Name')),
                ('Lower_Barrier', models.PositiveIntegerField()),
                ('Unit', models.CharField(max_length=10)),
                ('Price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shift_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shift_Name', models.CharField(choices=[('sm', 'Sunday Morning'), ('se', 'Sunday Evening'), ('mm', 'Monday Morning'), ('me', 'Monday Evening'), ('tm', 'Tuesday Morning'), ('te', 'Tuesday Evening'), ('wm', 'Wednesday Morning'), ('we', 'Wednesday Evening'), ('tm', 'Thursday Morning'), ('te', 'Thursday Evening'), ('fm', 'Friday Morning')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Supplier Name')),
                ('Email', models.EmailField(blank=True, max_length=254, verbose_name='')),
                ('phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be between 9 and 15 digits.', regex='^\\d{9,15}$')], verbose_name='Contact Phone')),
            ],
        ),
        migrations.CreateModel(
            name='User_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('ad', 'Admin'), ('br', 'Baker'), ('cs', 'Cashier')], default='cs', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Cashier_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Date', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('Customer_Name', models.CharField(max_length=50)),
                ('Customer_Last_Name', models.CharField(max_length=50)),
                ('PickUp_Date', models.DateField()),
                ('Comments', models.CharField(max_length=200)),
                ('Last_Modified', models.DateField(auto_now=True)),
                ('Order_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alexander.order_type')),
            ],
        ),
        migrations.CreateModel(
            name='Products_In_Cashier_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('comments', models.CharField(max_length=200)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='alexander.cashier_orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alexander.products')),
            ],
        ),
        migrations.CreateModel(
            name='Products_In_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField()),
                ('OrderNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alexander.orders_from_suppliers', verbose_name='Order')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alexander.raw_materials', verbose_name='Product')),
            ],
        ),
        migrations.AddField(
            model_name='raw_materials',
            name='Supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Product_List', to='alexander.suppliers'),
        ),
        migrations.AddField(
            model_name='orders_from_suppliers',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Orders_list', to='alexander.suppliers'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=15, unique=True)),
                ('Password', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Password must be at least 8 characters long and include at least one uppercase letter, one lowercase letter, one digit, and one special character.', regex='^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$')])),
                ('Employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alexander.employee')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alexander.user_types')),
            ],
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Shift_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alexander.shift_types')),
                ('Workers', models.ManyToManyField(related_name='my_shifts', to='alexander.user')),
            ],
        ),
        migrations.CreateModel(
            name='Shift_Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Is_Prefered', models.BooleanField(default=True)),
                ('Shift_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alexander.shift_types')),
                ('User', models.ManyToManyField(related_name='my_preferences', to='alexander.user')),
            ],
        ),
        migrations.AddField(
            model_name='orders_from_suppliers',
            name='Created_By',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Raw_Materials_Orders', to='alexander.user', verbose_name='Order submitted by'),
        ),
        migrations.AddField(
            model_name='cashier_orders',
            name='Created_By',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Orders_Submitted', to='alexander.user', verbose_name='Order submitted by'),
        ),
        migrations.AddField(
            model_name='cashier_orders',
            name='Last_Modified_By',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alexander.user'),
        ),
        migrations.CreateModel(
            name='Admin_Highlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Due_Date', models.DateField()),
                ('Text', models.TextField(max_length=1000)),
                ('Submitted_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alexander.user')),
            ],
        ),
        migrations.CreateModel(
            name='User_Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Is_Granted', models.BooleanField(default=True)),
                ('Permission_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alexander.permissions')),
                ('User', models.ManyToManyField(to='alexander.user')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField()),
                ('Stock_Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alexander.raw_materials', verbose_name='Item')),
            ],
        ),
    ]
