# Generated by Django 5.0.4 on 2024-06-12 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alexander', '0002_cashier_orders_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashier_orders',
            name='slug',
        ),
    ]
