# Generated by Django 5.0.4 on 2024-06-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexander', '0003_remove_cashier_orders_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashier_orders',
            name='Comments',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
