# Generated by Django 5.0.4 on 2024-06-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexander', '0004_alter_cashier_orders_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_in_cashier_orders',
            name='comments',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
