# Generated by Django 5.0.4 on 2024-06-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexander', '0006_cashier_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_type',
            name='Type',
            field=models.CharField(choices=[('הזמנה אונליין', 'Online_Order'), ('הזמנה מהדלפק', 'Desk_Order')], max_length=50),
        ),
    ]
