# Generated by Django 5.0.4 on 2024-06-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexander', '0007_alter_order_type_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_type',
            name='Type',
            field=models.CharField(choices=[('online_order', 'Online Order'), ('desk_order', 'Desk Order')], max_length=50),
        ),
    ]
