# Generated by Django 5.0.4 on 2024-06-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexander', '0008_alter_order_type_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_type',
            name='Type',
            field=models.CharField(choices=[('online_order', 'הזמנה אונליין'), ('desk_order', 'הזמנה בדלפק')], max_length=50),
        ),
    ]
