# Generated by Django 5.0.4 on 2024-06-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexander', '0009_alter_order_type_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashier_orders',
            name='Order_Type',
            field=models.CharField(choices=[('online_order', 'הזמנה אונליין'), ('desk_order', 'הזמנה בדלפק')], default='desk_order', max_length=50, verbose_name='סוג הזמנה'),
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='Stock_Item',
        ),
        migrations.RemoveField(
            model_name='orders_from_suppliers',
            name='supplier',
        ),
        migrations.AddField(
            model_name='orders_from_suppliers',
            name='supplier_List',
            field=models.ManyToManyField(related_name='Supplier_Orders', to='alexander.suppliers'),
        ),
        migrations.AddField(
            model_name='raw_materials',
            name='Quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='permission',
            field=models.CharField(choices=[('view_orders', 'הזמנות-צפייה'), ('edit_orders', ' הזמנות-עריכה'), ('view_stock', 'מלאי-צפייה'), ('edit_stock', 'מלאי-עריכה'), ('view_supplier_orders', 'הזמנות מספקים-צפייה'), ('edit_supplier_orders', 'הזמנות מספקים-עריכה'), ('view_schedule', 'משמרות-צפייה'), ('edit_schedule', 'משמרות-עריכה'), ('view_reports', 'דוחות-צפייה'), ('edit_reports', 'דוחות-עריכה'), ('view_control', 'בקרה-צפייה'), ('edit_control', 'בקרה-עריכה')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Order_Type',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
