# Generated by Django 5.0.4 on 2024-06-22 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexander', '0010_alter_cashier_orders_order_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw_materials',
            name='Material_Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='raw_materials',
            name='Supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_materials', to='alexander.suppliers'),
        ),
        migrations.AlterField(
            model_name='raw_materials',
            name='Unit',
            field=models.CharField(max_length=20),
        ),
    ]
