# Generated by Django 5.0.4 on 2024-06-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexander', '0011_alter_raw_materials_material_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_highlights',
            name='Type',
            field=models.CharField(choices=[('cs', 'עובד דלפק'), ('br', 'קונדיטור'), ('ad', 'מנהל'), ('al', 'כולם')], default='al', max_length=50),
        ),
    ]
