# Generated by Django 5.0.4 on 2024-07-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexander', '0013_employee_id_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Type',
            field=models.CharField(choices=[('ad', 'מנהל מערכת'), ('br', 'קונדיטור'), ('cs', 'עובד דלפק')], default='cs', max_length=2),
        ),
        migrations.DeleteModel(
            name='User_Types',
        ),
    ]
