# Generated by Django 5.0.4 on 2024-07-07 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexander', '0015_remove_user_permissions_user_user_permissions_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_permissions',
            name='User',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='alexander.user'),
        ),
    ]
