# Generated by Django 5.0.4 on 2024-07-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexander', '0016_alter_user_permissions_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_permissions',
            name='User',
        ),
        migrations.AddField(
            model_name='user_permissions',
            name='User',
            field=models.ManyToManyField(related_name='my_permissions', to='alexander.user'),
        ),
    ]
