# Generated by Django 5.0.4 on 2024-07-07 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexander', '0017_remove_user_permissions_user_user_permissions_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_permissions',
            name='User',
        ),
        migrations.AddField(
            model_name='user_permissions',
            name='User',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='alexander.user'),
            preserve_default=False,
        ),
    ]
