# Generated by Django 5.0.4 on 2024-07-07 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexander', '0019_remove_user_permissions_user_user_permissions_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_permissions',
            name='User',
        ),
        migrations.AddField(
            model_name='user_permissions',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_permissions', to='alexander.user'),
        ),
    ]
