# Generated by Django 5.0.4 on 2024-07-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexander', '0022_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashier_orders',
            name='IsPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='Category',
            field=models.CharField(choices=[('cake', 'עוגה'), ('bread', 'לחם'), ('other', 'אחר'), ('coockies', 'עוגיות')], default='other', max_length=50, null=True, verbose_name='קטגוריה'),
        ),
    ]
