# Generated by Django 5.0.4 on 2024-07-18 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexander', '0023_cashier_orders_ispaid_products_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift_preferences',
            name='User',
        ),
        migrations.AddField(
            model_name='shift_preferences',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_preferences', to='alexander.user'),
        ),
    ]
