# Generated by Django 5.0.4 on 2024-07-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexander', '0024_remove_shift_preferences_user_shift_preferences_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift_types',
            name='Shift_Name',
            field=models.CharField(choices=[('sm', 'ראשון-בוקר'), ('se', 'ראשון-ערב'), ('mm', 'שני-בוקר'), ('me', 'שני-ערב'), ('tm', 'שלישי-בוקר'), ('te', 'שלישי-ערב'), ('wm', 'רביעי-בוקר'), ('we', 'רביעי-ערב'), ('tm', 'חמישי-בוקר'), ('te', 'חמישי-ערב'), ('fm', 'שישי-בוקר')], max_length=2),
        ),
    ]
