# Generated by Django 5.0.4 on 2024-07-21 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexander', '0026_remove_shifts_workers_shifts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifts',
            name='User',
        ),
        migrations.AlterField(
            model_name='shift_types',
            name='Shift_Name',
            field=models.CharField(choices=[('sm', 'ראשון-בוקר'), ('se', 'ראשון-ערב'), ('mm', 'שני-בוקר'), ('me', 'שני-ערב'), ('tm', 'שלישי-בוקר'), ('te', 'שלישי-ערב'), ('wm', 'רביעי-בוקר'), ('we', 'רביעי-ערב'), ('thm', 'חמישי-בוקר'), ('the', 'חמישי-ערב'), ('fm', 'שישי-בוקר')], max_length=4),
        ),
        migrations.CreateModel(
            name='Users_in_Shifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alexander.shifts')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alexander.user')),
            ],
        ),
    ]
