# Generated by Django 5.1 on 2024-08-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexander', '0027_remove_shifts_user_alter_shift_types_shift_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Is_Active',
            field=models.BooleanField(default=True),
        ),
    ]
